server:
  port: 9080

spring:
  application:
    name: mayo-api-schedule
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/message_platform?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    # JPA DDL configuration properties
    generate-ddl: true
    show-sql: true
    # OSIV configuration property
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 수동 ACK , 자동 ACK 모드 활성화 하지 않는다. 목적은 에러 발생후 message 유실 되는걸 방지. 기본 값 : none
    listener:
      simple:
        acknowledge-mode: manual
  # Console 출력시 컬러 출력
  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml
  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: OFF # TRACE
